### ISSUE TITLE
Personal Google Hangouts message notification appeared during work Google Hangouts account full desktop share

### ISSUE THREAD

**Issue by hankfic** [bdkjones/MuzzleApp#12]
I ensured Muzzle daemon was running before sharing my desktop on a Google Hangout using my work account.  I just got finished telling everyone on the Hangout that they probably saw the Product Hunt featured product Muzzle and what a great idea it is that it'll block embarrassing notifications from my wife displaying.  An embarrassing notification from my wife promptly displays.  I go back to sharing only my browser.  The notification that displayed was from my personal Google account and was a Hangouts message.

**Comment by bdkjones** [comment]
Was the notification a Chrome notification? Muzzle stops macOS notes; it won't do anything about chrome's internal notifications. You can, however, set Chrome to post its notifications through macOS rather than on its own and then Muzzle will stop them. That's available in chrome's flags;  quick google search will turn it up.

Or, alternately, use a non-creepy browser: Safari.

**Comment by hankfic** [comment]
Ahh, yes it must've been.  For some reason enabling chrome://flags/#enable-native-notifications isn't working for me on Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by hankfic** [comment]
Anyhow, not your issue.  Thanks for the support.  Closing this one out.
