### ISSUE TITLE
Notification examples on your website are bad and unacceptable

### ISSUE THREAD

**Issue by debo** [bdkjones/MuzzleApp#68]
I don't think I need to explain this issue any further, the majority of the notification examples are quite denigratory and stereotyping of a series of categories and minorities, which I find quite unacceptable and inappropriate. You should definitely keep the examples clean and safe in my personal opinion. Please think about reconsidering your position on those.

Thanks a lot.

**Comment by bdkjones** [comment]
I’m unable to tell if this was sarcasm. If it was, sorry for missing the joke.

If it was not:

I have no doubt that if you and I sat down for drinks in person, we’d get along famously. Short of that, I’d highly recommend listening to this podcast episode: 

https://youtu.be/NIxhH85cQMY

It will produce massive amounts of cognitive dissonance, but just get through the whole thing and you’ll have a better understanding of where I’m coming from: the world is not a massive collection of racist, misogynistic, assholes. Jokes are just jokes and the constant pressure to publicly display offense at innocuous things so as to prove our own morality and righteousness is a detriment to society.

There is nothing offensive about Muzzle’s notification examples precisely because the people behind them do not *intend* to offend. In the future, I’d recommend assessing someone’s intent before declaring that something they’ve said is offensive or racist, etc.
